spring:
  datasource:
#    jndi-name: jdbc/gfnDB     # jndi 설정
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

#debug: true
logging:
  level:
    com.nexgrid.cgsg.admin.mapper : info
  config: classpath:log4j2-local.xml

mybatis:
  type-aliases-package: com.nexgrid.cgsg.admin.vo
  mapper-locations: classpath:mapper/**/*.xml

cgsg:
  aliveLog:
    milliseconds: 300000     # 감시용 로그 기록되는 밀리세컨드
--- ## 개발
spring:
  profiles: local
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@nexgrid2.iptime.org:11522:ADCBDBO
    username: gfn
    password: gfn

server:
  servlet:
    context-path: /api
  port: 8080

--- ## 테스트
spring:
  profiles: test
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@nexgrid2.iptime.org:11522:ADCBDBO
    username: gfn
    password: gfn

server:
  servlet:
    context-path: /api
  port: 8080

--- ## 개발
spring:
  profiles: dev
  datasource:
    jndi-name: jdbc/gfnDB
logging:
  config: classpath:log4j2-real.xml

